### PR TITLE
Mention filename required by update_users

### PR DESCRIPTION
**Pull request by dragonfi**

### CODE REVIEW

**Comment by dragonfi** [comment]
@feanil @jarv Hi, can you pull this please. It's just some readme change.

As for the contributor agreement, @antoviaque can explain, but I'm basically from his organization. (That have signed a contributor agreement.) (See discussion in https://github.com/Stanford-Online/edx-theme/pull/9)

**Comment by feanil** [comment]
@nedbat what's the procedure on verifying that someone is from a partner organization?

**Comment by nedbat** [comment]
@feanil Xavier has vouched for @dragonfi, so he's good to go.

**Comment by e0d** [comment]
:+1:

**Pull request merged**
