### PR TITLE
Use RABBIT_HOST in env.json if it exists

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by shnayder** [comment]
code looks fine, though I'm not sure where this came from before, or the reasons for changing it now.

**Comment by jarv** [comment]
Sorry should have mentioned in the pull request that this is for specifying a different host for the rabbitmq other than localhost which is the default in settings.  the intention is to run rabbitmq on a different set of servers.  The reason for doing this now is so that our rabbitmq servers are setup for high availability.

**Comment by shnayder** [comment]
Ok, sounds good.  Merged.  Yay high availability.  Can we set up celery on them now?

**Comment by jarv** [comment]
Yeah, I don't see why not.

**Pull request merged**
