### PR TITLE
Use boto3 and modern django-storages

### PR DESCRIPTION
**Pull request by jibsheet**

### CODE REVIEW

**Comment by jibsheet** [comment]
@bradenmacdonald @antoviaque Is there someone from OpenCraft who can test the swift upgrade here?  We were stuck on a weird fork of django-storage preventing the use of boto3 and I'd like to remove that upgrade hurdle.

**Comment by bradenmacdonald** [comment]
@jibsheet  Sure, thanks for asking. @pomegranited  or @UmanShahzad do you have time to give this a spin?

**Comment by pomegranited** [comment]
Sure thing @bradenmacdonald  CC @UmanShahzad .
@jibsheet  I'll do my best to get this tested by Friday, but it might be next week.  Is that ok?

**Comment by jibsheet** [comment]
@pomegranited that's totally fine.  I'm off Friday.  My only real goal is I'd love to get the upgrade pulled into Hawthorne with all the other bugfixes we landed.  We've got about 3 other things I'm trying to land and call XQueue "improved and stable again"

**Review by xitij2000 — COMMENTED** [review]
I've tested these changes on a Sandbox and they seem to be working fine for us SWIFT and S3. So :+1:

**Comment by bradenmacdonald** [comment]
@jibsheet Based on @xitij2000's review then, this is good to go from OpenCraft's perspective. Thanks again for the ping, and sorry for the delay in reviewing.

**Comment by jibsheet** [comment]
Thanks @xitij2000 and @bradenmacdonald  - no worries on the delay, my whole week was consumed with some other internal work.  I'm finishing merging some configuration changes and then this will land early next week.

**Review by feanil — APPROVED** [review]

**Pull request merged**
