### PR TITLE
Add missing rabbitmq VHOST parameter in worker class

### PR DESCRIPTION
**Pull request by carsongee**
It looks like one got missed from PR #74, adding it.

@jbau @rocha

### CODE REVIEW

**Comment by rocha** [comment]
Good catch.

:+1:

**Comment by carsongee** [comment]
FYI, I don't have merge on xqueue.

**Comment by rocha** [comment]
I'll merge it once we hear back from @jbau

**Comment by jbau** [comment]
LGTM.  I dunno how i missed this. =(

**Pull request merged**
