### PR TITLE
change requirements to use git https clone

### PR DESCRIPTION
**Pull request by xiangjf**
Change requirements line for pika to use git https clone, as many corporates' firewall blocks the port for git protocol.
Also, requirements of other repos in edx use https clone as well.

### CODE REVIEW

**Comment by nedbat** [comment]
@xiangjf Thanks for this pull request, sorry it took so long for us to get to it.

1) Can you please sign and return a Contributor's Agreement, as outlined in the edx-platform CONTRIBUTING file?  And/or, if you are affiliated with an institution, that is also helpful information.

2) Rather than merging master into your pull request, can you rebase on top of master? That keeps the commit history cleaner.  Thanks.

**Comment by xiangjf** [comment]
@nedbat I have sent the signed Contributor's Agreement and rebased my pull request, thank you.

**Comment by e0d** [comment]
Looks good to me :+1:

**Comment by nedbat** [comment]
@xiangjf Thanks for the signed agreement!
This is good to merge.

**Comment by jzoldak** [comment]
@nedbat @e0d this broke master xqueue.
http://jenkins.edx.org:8080/job/xqueue/327/console

**Comment by e0d** [comment]
@jzoldak 

The issue seems to be that the test script doesn't or a clean venv or pass -w when installing an updated requirement

```
18:44:03   git clone in /mnt/virtualenvs/xqueue/src/pika exists with URL git://github.com/pika/pika.git
18:44:03   The plan is to install the git repository https://github.com/pika/pika.git
18:44:03 What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup Exception:
18:44:03 Traceback (most recent call last):
```

**Comment by jzoldak** [comment]
@e0d thanks for the troubleshooting.
I've wiped out the workspace for the job and kicked off another manual run.

Update: that build failed too, but I don't have time to look into it unfortunately.

**Comment by e0d** [comment]
@jzoldak It's the same error, so the venv must have survived wiping the work space.

Adding `--exists-action w` to the script should address this or forcing the venv to be re-created.

**Pull request merged**
