### PR TITLE
truncate lms_callback_url to 128

### PR DESCRIPTION
**Pull request by muhammad-ammar**
This is needed for Django 1.8.

Please see the details at 
https://github.com/edx/xqueue/pull/99
https://github.com/edx/xqueue/pull/98#discussion_r39977589

### CODE REVIEW

**Comment by muhammad-ammar** [comment]
@feanil @nedbat @muzaffaryousaf @symbolist @doctoryes @macdiesel Please review. Thanks!

**Comment by doctoryes** [comment]
Questions:
- Do you plan to merge #99 first? Or close it? That PR changes the field length - I assume you intend to close it?
- Do any tests exist in xqueue that test a truncated lms_callback_url?

**Comment by muhammad-ammar** [comment]
@doctoryes I have closed https://github.com/edx/xqueue/pull/99. It is not needed. I am unable to find any test in xqueue that is testing truncated lms_callback_url.

**Comment by macdiesel** [comment]
:+1:

**Comment by symbolist** [comment]
:+1:

**Pull request merged**
