### PR TITLE
[BD-6] Update tests to run using python 3.8.

### PR DESCRIPTION
**Pull request by ericfab179**
Run tests using python 3.5 and python 3.8 in the Docker container.
Re-opening this PR https://github.com/edx/xqueue/pull/743 since edx bot does not allowed me to re-open it.

**Reviewers**
- [ ] @awais786 
- [ ] @morenol

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ericfab179! I've created [OSPR-4555](https://openedx.atlassian.net/browse/OSPR-4555) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by mzulqarnain1 — APPROVED** [review]

**Review by UsamaSadiq — APPROVED** [review]

**Comment by morenol** [comment]
The tests are failing because they are using python2.7

**Comment by openedx-webhooks** [comment]
@ericfab179 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue&entry.867055334=https://github.com/edx/xqueue/pull/744&entry.1484655318=https://github.com/ericfab179&entry.752974735=2020-05-19+00:21&entry.1917517419=2020-05-22+22:57&entry.2133058324=No) so we can improve your experience in the future.

**Review by awais786 — APPROVED** [review]

**Comment by awais786** [comment]
@ericfab179 Please squash

**Comment by ericfab179** [comment]
@awais786 Squashed.

**Comment by openedx-webhooks** [comment]
@ericfab179 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue&entry.867055334=https://github.com/edx/xqueue/pull/744&entry.1484655318=https://github.com/ericfab179&entry.752974735=2020-05-19+00:21&entry.1917517419=2020-05-28+09:51&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
