### PR TITLE
Upload submission to one bucket instead of one per queue

### PR DESCRIPTION
**Pull request by rocha**
The paramater S3_BUCKET must be set to the destination bucket

### CODE REVIEW

**Comment by rocha** [comment]
@fephsun @e0d sanity check? Thanks!

**Comment by rocha** [comment]
The parameter S3_BUCKET must be set in the env.json during deployment to AWS.

**Comment by fephsun** [comment]
Looks good to me.

**Comment by rocha** [comment]
@cpennington can you take a look? We ran out of buckets on S3.

**Comment by cpennington** [comment]
Looks good. Are we going to migrate the existing uploads in the disparate buckets to the central bucket? Also, do the graders know now what bucket the files are in? Or do we just hand them a url?

**Comment by rocha** [comment]
Yes, we are going to unify the existing buckets into one. Right now, we have around 30 submission buckets.

We pass a URL to the graders, which should be ok, unless they are keeping a record on the graders side. After talking to the relevant parties, it seems that none is doing so. We should however provide an easy way to map from the old locations to the new ones.

**Comment by feanil** [comment]
looks good to me.

**Pull request merged**
