### PR TITLE
PROD-389: Run python modernize on the repo

### PR DESCRIPTION
**Pull request by jinder1s**
Run python modernize on the repo.

Specifically: `python-modernize  -w .`
This work is for [PROD-389](https://openedx.atlassian.net/secure/RapidBoard.jspa?rapidView=537&modal=detail&selectedIssue=PROD-389). This is part of the effort to convert code base from python 2.7 to python 3.

### CODE REVIEW

**Comment by jinder1s** [comment]
The decrease in code coverage of 0.16% seems mostly harmless, do I need to do something about this?

**Comment by fysheets** [comment]
> The decrease in code coverage of 0.16% seems mostly harmless, do I need to do something about this?

I think that's fine. One ask is to add a link to the ticket in the description here as well as a short description as to why you're completing this task.

**Comment by fysheets** [comment]
@jinder1s / @feanil for my own knowledge, are the `.bak` files created here expected / does that happen with every python-modernize run?

**Comment by jinder1s** [comment]
You are correct, the .bak files are not suppose to exist. I will check why they remained after run.

**Comment by feanil** [comment]
python-modernize usually creates .bak files.  They should not be checked in as a part of your change.  Let me know when this is ready for review again.

**Comment by jinder1s** [comment]
This PR should now be ready for a full review.

**Review by feanil — APPROVED** [review]

**Comment by feanil** [comment]
Don't forget to make sure that this gets deployed to production.

**Comment by fysheets** [comment]
Thanks Feanil -- we can deploy it together once things have generally calmed down.

**Pull request merged**
