### PR TITLE
Changed 'queue' app name to 'queue_app' to avoid name collision

### PR DESCRIPTION
**Pull request by gsidebo**
This PR facilitates local development (using a Vagrant VM in my case) by renaming the `queue` app to `queue_app`. In my local dev environment, `queue` could not be imported due to a [naming collision](https://github.com/requests/requests/blob/v0.14.2/requests/packages/urllib3/connectionpool.py#L22) with `urllib3` in the `requests` library, making it impossible to run the app. [This guide](https://openedx.atlassian.net/wiki/spaces/PLAT/pages/51937339/XQueue+Development+Setup) discusses local xqueue development, but neither approach in the guide successfully avoids the naming collision issue. Renaming the django app avoids this collision and enables local development.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @gsidebo! I've created [OSPR-1994](https://openedx.atlassian.net/browse/OSPR-1994) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/xqueue/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
I would have thought "xqueue" would be a natural choice for the new name.

This seems like a big change.  How have others managed local development without this change?  Are you using a dedicated virtualenv for xqueue? That might prevent collisions.

**Comment by gsidebo** [comment]
@nedbat Unfortunately `xqueue` is already taken: https://github.com/edx/xqueue/tree/master/xqueue. I tried using a virtualenv during my first attempt at running this locally, but didnt have any luck. That was a while ago, and I may have missed a step somewhere. I'll try that again and report back here

**Comment by gsidebo** [comment]
@nedbat virtualenv didn't work:

```
(xqueue) vagrant@precise64:~/xqueue$ which python
/home/vagrant/.virtualenvs/xqueue/bin/python
(xqueue) vagrant@precise64:~/xqueue$ python ./manage.py shell
2017-11-02 16:03:59,213 WARNING 16131 [py.warnings] base.py:57 - /home/vagrant/.virtualenvs/xqueue/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py:57: RuntimeWarning: SQLite received a naive datetime (2017-11-02 16:03:59.212825) while time zone support is active.
  RuntimeWarning)

Python 2.7.9 (default, Nov  2 2017, 19:36:21)
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from queue.ext_interface import get_queuelen
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-56eddbcafeec> in <module>()
----> 1 from queue.ext_interface import get_queuelen

/home/vagrant/xqueue/queue/ext_interface.py in <module>()
      6 from django.utils import timezone
      7 from statsd import statsd
----> 8 from requests.exceptions import ConnectionError, Timeout
      9 import requests
     10

/home/vagrant/.virtualenvs/xqueue/lib/python2.7/site-packages/requests/__init__.py in <module>()
     50
     51
---> 52 from . import utils
     53 from .models import Request, Response
     54 from .api import request, get, head, post, patch, put, delete, options

......

/home/vagrant/.virtualenvs/xqueue/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py in <module>()
     20     from queue import LifoQueue, Empty, Full
     21 except ImportError:
---> 22     from Queue import LifoQueue, Empty, Full
     23
     24

ImportError: cannot import name LifoQueue
```

As for how other developers have managed to hack on this locally, I honestly have no idea. The existence of [this guide](https://openedx.atlassian.net/wiki/spaces/PLAT/pages/51937339/XQueue+Development+Setup) suggests to me that this has been a problem for a while now

**Comment by gsidebo** [comment]
@nedbat Let me know if you want to discuss this a little more. It's a big change for sure, but I've tried to take some steps to minimize the risk (leaving the submissions table name unchanged, testing the migrations from a fresh install as well as the scenario where the `queue` app already exists). I could also add some more documentation around this. For example I could create a gist (et. al.) that would describe the process for rolling back this change, and/or a new local development guide that would replace the one I linked above

EDIT: Also, if anyone has any bandwidth, it would be great to get my [xqueue-watcher PR](https://github.com/edx/xqueue-watcher/pull/29) reviewed as well!

**Comment by nedbat** [comment]
@edx/platform-team (particularly @doctoryes) please take a look at this.

**Comment by macdiesel** [comment]
@doctoryes was it @estute who was going going to be the steward of the xqueue? 

This is going to require not just the changes in the code, but the database will also need to be updated to reflect this change. Possibly other things. This fix is very disruptive to edx operations. I'm a no on this.

**Review by macdiesel — CHANGES_REQUESTED** [review]
I would prefer we did not do this.

**Comment by gsidebo** [comment]
@macdiesel The database changes in production would be limited to an update to one row each in two Django tables (`django_content_type` and `django_migrations`), and those changes would be automatically applied upon deployment since it's part of the migrations. The database table name would not change, and the meta-option that pins the table name [does not affect the database](https://docs.djangoproject.com/en/1.11/ref/migration-operations/#altermodeloptions). Do you expect any other database changes from this? Can you provide some more detail about your concerns regarding the disruption to edx operations?

Either way, if this PR is rejected, I don't see a clear path forward to hack on this project and run it locally. If your team is able to do that, I would appreciate any guidance you can provide.

**Comment by macdiesel** [comment]
@gsidebo These tests run fine with a clean virtual env:
```
➜  xqueue git:(master) ✗ rm -Rf .python 
➜  xqueue git:(master) ✗ virtualenv --clear -p python2.7 .python
Running virtualenv with interpreter /usr/bin/python2.7
Not deleting .python/bin
New python executable in .python/bin/python
Installing setuptools, pip, wheel...source ^[[Adone.
➜  xqueue git:(master) ✗ source .python/bin/activate
➜  xqueue git:(master) ✗ pip freeze
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
wheel==0.24.0
➜  xqueue git:(master) ✗ pip install -r requirements.txt 
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting django<1.9,>=1.8 (from -r requirements.txt (line 1))
  Using cached Django-1.8.18-py2.py3-none-any.whl
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 2))
Collecting argparse==1.2.1 (from -r requirements.txt (line 3))
Collecting boto==2.39.0 (from -r requirements.txt (line 4))
  Using cached boto-2.39.0-py2.py3-none-any.whl
Collecting coverage==3.6b1 (from -r requirements.txt (line 5))
Collecting django-nose==1.4.1 (from -r requirements.txt (line 6))
  Using cached django_nose-1.4.1-py2-none-any.whl
Collecting dogstatsd-python==0.2 (from -r requirements.txt (line 7))
Collecting edx-django-release-util==0.3.0 (from -r requirements.txt (line 8))
  Using cached edx_django_release_util-0.3.0-py2-none-any.whl
Collecting gunicorn==0.16.1 (from -r requirements.txt (line 9))
Collecting newrelic==2.64.0.48 (from -r requirements.txt (line 10))
Collecting nose==1.2.1 (from -r requirements.txt (line 11))
Collecting nosexcover==1.0.7 (from -r requirements.txt (line 12))
Collecting path.py==2.4.1 (from -r requirements.txt (line 13))
Obtaining pika from git+https://github.com/pika/pika.git@a731347fc0#egg=pika (from -r requirements.txt (line 14))
  Cloning https://github.com/pika/pika.git (to a731347fc0) to ./.python/src/pika
  Could not find a tag or branch 'a731347fc0', assuming commit.
Collecting python-termstyle==0.1.10 (from -r requirements.txt (line 15))
Collecting rednose==0.3 (from -r requirements.txt (line 16))
Collecting requests==0.14.2 (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7 (from -r requirements.txt (line 18))
Collecting mock==2.0.0 (from -r requirements.txt (line 19))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting django-storages-redux==1.3.1 (from -r requirements.txt (line 20))
  Using cached django_storages_redux-1.3.1-py2.py3-none-any.whl
Collecting six<2.0.0,>=1.10.0 (from edx-django-release-util==0.3.0->-r requirements.txt (line 8))
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting PyYAML>=3.11 (from edx-django-release-util==0.3.0->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./.python/lib/python2.7/site-packages (from python-termstyle==0.1.10->-r requirements.txt (line 15))
Collecting funcsigs>=1 (from mock==2.0.0->-r requirements.txt (line 19))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->-r requirements.txt (line 19))
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Installing collected packages: django, MySQL-python, argparse, boto, coverage, nose, django-nose, dogstatsd-python, six, PyYAML, edx-django-release-util, gunicorn, newrelic, nosexcover, path.py, pika, python-termstyle, rednose, requests, funcsigs, pbr, mock, django-storages-redux
  Running setup.py develop for pika
Successfully installed MySQL-python-1.2.5 PyYAML-3.12 argparse-1.2.1 boto-2.39.0 coverage-3.6b1 django-1.8.18 django-nose-1.4.1 django-storages-redux-1.3.1 dogstatsd-python-0.2 edx-django-release-util-0.3.0 funcsigs-1.0.2 gunicorn-0.16.1 mock-2.0.0 newrelic-2.64.0.48 nose-1.2.1 nosexcover-1.0.7 path.py-2.4.1 pbr-3.1.1 pika python-termstyle-0.1.10 rednose-0.3 requests-0.14.2 six-1.11.0
➜  xqueue git:(master) ✗ 2017-11-07 11:35:32,919 ERROR 92626 [pika.adapters.base_connection] base_connection.py:303 - Read empty data, calling disconnect
2017-11-07 11:35:32,919 ERROR 92626 [pika.adapters.base_connection] base_connection.py:303 - Read empty data, calling disconnect

➜  xqueue git:(master) ✗ rake test 
python manage.py test --settings xqueue.test_settings --noinput
2017-11-07 11:35:48,632 DEBUG 93155 [nose.plugins.manager] manager.py:385 - DefaultPluginManager load plugin NOSETESTS_PLUGINS = rednose:RedNose
2017-11-07 11:35:48,643 DEBUG 93155 [nose.plugins.manager] manager.py:385 - DefaultPluginManager load plugin xcover = nosexcover:XCoverage
nosetests --cover-erase --with-xunit --with-xcoverage --cover-html --cover-inclusive --cover-html-dir /Users/brianbeggs/workspace/xqueue/reports/cover --cover-package queue queue --verbosity=1
2017-11-07 11:35:48,764 DEBUG 93155 [nose.plugins.manager] manager.py:385 - DefaultPluginManager load plugin NOSETESTS_PLUGINS = rednose:RedNose
2017-11-07 11:35:48,765 DEBUG 93155 [nose.plugins.manager] manager.py:385 - DefaultPluginManager load plugin xcover = nosexcover:XCoverage
Creating test database for alias 'default'...
2017-11-07 11:35:49,508 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime(6) NOT NULL); (params None)
2017-11-07 11:35:49,813 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); (params None)
2017-11-07 11:35:49,829 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `django_content_type` ADD CONSTRAINT `django_content_type_app_label_45f3b1d93ec8c61c_uniq` UNIQUE (`app_label`, `model`); (params [])
2017-11-07 11:35:49,845 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; (params [])
2017-11-07 11:35:49,865 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `django_content_type` DROP COLUMN `name` CASCADE; (params [])
2017-11-07 11:35:49,883 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL, UNIQUE (`content_type_id`, `codename`)); (params None)
2017-11-07 11:35:49,903 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); (params None)
2017-11-07 11:35:49,912 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`group_id`, `permission_id`)); (params None)
2017-11-07 11:35:49,934 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime(6) NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime(6) NOT NULL); (params None)
2017-11-07 11:35:49,947 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `auth_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL, UNIQUE (`user_id`, `group_id`)); (params None)
2017-11-07 11:35:49,957 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `auth_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`user_id`, `permission_id`)); (params None)
2017-11-07 11:35:49,965 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_permission` ADD CONSTRAINT `auth__content_type_id_508cf46651277a81_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
2017-11-07 11:35:49,980 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permission_group_id_689710a9a73b7457_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
2017-11-07 11:35:49,997 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group__permission_id_1f49ccbbdc69d2fc_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
2017-11-07 11:35:50,014 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_4b5ed4ffdb8fd9b0_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
2017-11-07 11:35:50,028 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_group_id_33ac548dcf5f8e37_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
2017-11-07 11:35:50,047 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissi_user_id_7f0938558328534a_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
2017-11-07 11:35:50,060 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_u_permission_id_384b62483d7071f0_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
2017-11-07 11:35:50,097 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; (params [])
2017-11-07 11:35:50,126 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_user` MODIFY `email` varchar(254) NOT NULL; (params [])
2017-11-07 11:35:50,173 DEBUG 93155 [django.db.backends.schema] schema.py:102 - ALTER TABLE `auth_user` MODIFY `last_login` datetime(6) NULL; (params [])
2017-11-07 11:35:50,194 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `queue_submission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `requester_id` varchar(128) NOT NULL, `lms_callback_url` varchar(128) NOT NULL, `queue_name` varchar(128) NOT NULL, `xqueue_header` varchar(1024) NOT NULL, `xqueue_body` longtext NOT NULL, `s3_keys` varchar(1024) NOT NULL, `s3_urls` varchar(1024) NOT NULL, `arrival_time` datetime(6) NOT NULL, `pull_time` datetime(6) NULL, `push_time` datetime(6) NULL, `return_time` datetime(6) NULL, `grader_id` varchar(128) NOT NULL, `pullkey` varchar(128) NOT NULL, `grader_reply` longtext NOT NULL, `num_failures` integer NOT NULL, `lms_ack` bool NOT NULL, `retired` bool NOT NULL); (params None)
2017-11-07 11:35:50,201 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE INDEX `queue_submission_38e86929` ON `queue_submission` (`lms_callback_url`); (params [])
2017-11-07 11:35:50,206 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE INDEX `queue_submission_692e12dd` ON `queue_submission` (`queue_name`); (params [])
2017-11-07 11:35:50,213 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE INDEX `queue_submission_a5597e89` ON `queue_submission` (`retired`); (params [])
2017-11-07 11:35:50,224 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime(6) NOT NULL); (params None)
2017-11-07 11:35:50,232 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`); (params [])
2017-11-07 11:35:50,243 DEBUG 93155 [django.db.backends.schema] schema.py:102 - CREATE TABLE `django_site` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `domain` varchar(100) NOT NULL, `name` varchar(50) NOT NULL); (params None)
........127.0.0.1 - - [07/Nov/2017 11:35:51] "POST / HTTP/1.1" 200 -
.......SSSS2017-11-07 11:35:54,729 INFO 93155 [queue.consumer] consumer.py:281 -  [1] Starting consumer for queue test_queue_1bb4f156a3744a9398f3e57dbd07f91c
2017-11-07 11:35:54,730 INFO 93155 [queue.consumer] consumer.py:288 - [1] - Attempting to establish a connection for queue test_queue_1bb4f156a3744a9398f3e57dbd07f91c
2017-11-07 11:35:54,787 INFO 93155 [queue.consumer] consumer.py:355 - Processing submission from queue_name: test_queue_1bb4f156a3744a9398f3e57dbd07f91c, submission_id: 1
127.0.0.1 - - [07/Nov/2017 11:35:54] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [07/Nov/2017 11:35:54] "POST / HTTP/1.1" 200 -
.2017-11-07 11:35:56,889 INFO 93155 [queue.consumer] consumer.py:313 -  [1] Consumer for queue test_queue_1bb4f156a3744a9398f3e57dbd07f91c is exiting normally...
2017-11-07 11:35:56,971 INFO 93155 [queue.consumer] consumer.py:320 -  [1] Consumer for queue test_queue_1bb4f156a3744a9398f3e57dbd07f91c stopped


..
Name                                                   Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------
queue                                                      0      0   100%   
queue.consumer                                           193     37    81%   46, 68-73, 127-136, 168-169, 183, 189-191, 194-195, 246-255, 361-363, 372-376, 391-398, 417, 432-434, 442
queue.ext_interface                                      106     36    66%   36-45, 56-57, 85-103, 123, 128-132, 136-143, 146, 177-178, 182-183, 186, 190
queue.lms_interface                                       88     18    80%   33-34, 40-45, 68-73, 153-160
queue.management                                           0      0   100%   
queue.management.commands                                  0      0   100%   
queue.management.commands.push_orphaned_submissions       36     23    36%   19-23, 26-52
queue.management.commands.queue_ungraded_submissions      62      2    97%   100-101
queue.management.commands.requeue_pulled_submissions      34     22    35%   18-28, 32-47
queue.management.commands.retire_submissions              35     22    37%   25-39, 43-54
queue.management.commands.run_consumer                    67     33    51%   73-94, 98-125
queue.management.commands.update_users                    29     19    34%   24-47
queue.migrations                                           0      0   100%   
queue.migrations.0001_initial                              6      0   100%   
queue.models                                              41     40     2%   7-69
queue.producer                                            30      7    77%   20, 36-41
queue.urls                                                 4      0   100%   
queue.util                                                10      0   100%   
queue.views                                               25      3    88%   39-40, 45
queue.xqueue_client                                       23     14    39%   15-18, 21-25, 28-52
------------------------------------------------------------------------------------
TOTAL                                                    789    276    65%   
----------------------------------------------------------------------
Ran 22 tests in 20.270s

OK (SKIP=4)
Destroying test database for alias 'default'...
➜  xqueue git:(master) ✗ 
➜  xqueue git:(master) ✗ 
➜  xqueue git:(master) ✗ pip freeze 
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
boto==2.39.0
coverage==3.6b1
Django==1.8.18
django-nose==1.4.1
django-storages-redux==1.3.1
dogstatsd-python==0.2
edx-django-release-util==0.3.0
funcsigs==1.0.2
gunicorn==0.16.1
mock==2.0.0
MySQL-python==1.2.5
newrelic==2.64.0.48
nose==1.2.1
nosexcover==1.0.7
path.py==2.4.1
pbr==3.1.1
-e git+https://github.com/pika/pika.git@a731347fc07812401201e9415141059ebfb86c4a#egg=pika-dev
python-termstyle==0.1.10
PyYAML==3.12
rednose==0.3
requests==0.14.2
six==1.11.0
wheel==0.24.0
➜  xqueue git:(master) ✗ git diff > test.diff
➜  xqueue git:(master) ✗ cat test.diff 
diff --git a/xqueue/test_settings.py b/xqueue/test_settings.py
index e1eb63c..5f2c9ce 100644
--- a/xqueue/test_settings.py
+++ b/xqueue/test_settings.py
@@ -33,7 +33,11 @@ DATABASES = {
         },
 
         # Wrap all view methods in an atomic transaction automatically.
-        'ATOMIC_REQUESTS': True
+        'ATOMIC_REQUESTS': True,
+        'USER': 'root',
+        'PASSWORD': '',
+        'HOST': '127.0.0.1',
+        'PORT': '3306',
     }
 }
 
@@ -64,8 +68,8 @@ except (IOError, ValueError):
 # RabbitMQ configuration
 # Default to local broker if no external
 # broker defined in test_env.json
-RABBITMQ_USER = ENV_TOKENS.get('RABBITMQ_USER', 'guest')
-RABBITMQ_PASS = ENV_TOKENS.get('RABBITMQ_PASS', 'guest')
+RABBITMQ_USER = ENV_TOKENS.get('RABBITMQ_USER', 'user')
+RABBITMQ_PASS = ENV_TOKENS.get('RABBITMQ_PASS', 'user')
 RABBIT_HOST = ENV_TOKENS.get('RABBIT_HOST', 'localhost')
 RABBIT_PORT = ENV_TOKENS.get('RABBIT_PORT', 5672)
 RABBIT_VHOST = ENV_TOKENS.get('RABBIT_VHOST', '/')
```

This code code runs well in production, requires little maintenance, almost never alarms. We are not planning on adding any new features and the team does not plan to touch this code. I appreciate you taking the time to submit this PR, but your error is operational in nature and is not due to an error in the code.

**Comment by openedx-webhooks** [comment]
@gsidebo Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue&entry.867055334=https://github.com/edx/xqueue/pull/124&entry.1484655318=https://github.com/gsidebo&entry.752974735=2017-11-02+18:43&entry.1917517419=2017-11-07+16:39&entry.2133058324=No) so we can improve your experience in the future.

**Comment by nedbat** [comment]
Our own @doctoryes had encountered similar problems when he wrote this page: https://openedx.atlassian.net/wiki/spaces/PLAT/pages/51937339/XQueue+Development+Setup

Are they resolved now? Seems like we don't have a shared understanding of how this code behaves in a development setup.

**Comment by macdiesel** [comment]
This morning I tested this a few times each with a clean virtual env and did not encounter these issues. The issues @gsidebo was seeing are due to having a python env that has artifacts in it that are not used in this product.

**Comment by doctoryes** [comment]
IIRC I got the Vagrant-based solution described in that page to work for local development - though it was hacky since I deployed code changes via Github push/pull. I abandoned my development to work on a different project.

If I were picking this up again today, I'd pursue a Docker-based development solution. The configuration repo already has a Dockerfile which can be used to build/run a xqueue Docker container here:
https://github.com/edx/configuration/tree/master/docker/build/xqueue

**Pull request closed without merging**
