### PR TITLE
Travisifying

### PR DESCRIPTION
**Pull request by puhrez**
travisified xqueue

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xbs13! I've created [OSPR-526](https://openedx.atlassian.net/browse/OSPR-526) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) or indicated your institutional affiliation and added yourself to the [AUTHORS](https://github.com/edx/xqueue/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
Why did the travis build fail? :( (cc @feanil or @benpatterson  - looks like maybe a problem building distribute?)

**Comment by benpatterson** [comment]
I realize this is a lame question, but have you tried `python: "2.7"` all on one line?

**Comment by puhrez** [comment]
Not lame, thought about it, but having the list makes it easily extensible when / if 3 ever gets supported.

**Comment by puhrez** [comment]
Any clue as to this "No module named **main**" error?

**Comment by benpatterson** [comment]
@xbs13 you can try `nosetests --with-coverage`. That should get the tests to run with coverage. (It can be further refined by package, etc. Ultimately you might want something like `nosetests --with-coverage --cover-package <packages>`.)

That said, I did run tests locally with nosetests, and am running into a missing environment variable. That is likely the next thing to tackle once the nose command is sorted out.

**Comment by benpatterson** [comment]
BTW once that is done, pep8 might need a .pep8 file...I'm not available now, but will have time this afternoon if you'd like further review or a closer look...

**Comment by puhrez** [comment]
So, I've found two similiar bugs to this on the internet, both from open edx sources:
- [google forum](https://groups.google.com/forum/#!topic/edx-code/j0ar0UMfZX4)
- [jira](https://openedx.atlassian.net/browse/TE-424)

but neither of them offer solutions that fit this case. Anyways still doing research.

**Comment by benpatterson** [comment]
@xbs13 I was just looking at this and found something that might really help push things along!

I noticed that we already have some test infrastructure in this repo. See the README under the test_framework folder [here](https://github.com/edx/xqueue/tree/master/test_framework). Looks like we are using rake to run these tests, and that rabbitmq is a requirement.

I see in the Travis docs, that rabbitmq can get installed by using a `services` setting. See here: http://docs.travis-ci.com/user/database-setup/#RabbitMQ

So, you may be able to just make sure rabbitmq is available and run `rake test.`

What I don't know offhand is if you'll need to get ruby onto the machine as well. I'll see if I find any other of our repos using rake...

**Comment by benpatterson** [comment]
Here is an example of one of our repos that is more dependent on ruby ([link](https://github.com/edx/cs_comments_service/blob/master/.travis.yml)).

In the case of xqueue, you may need BOTH python and ruby available. It might be a matter of using the rvm setting like the link does, but setting language to python. I would recommend setting the rvm to 1.9.3 for this repo, unless you can find doc specifying a different ruby version to use. If, using the rvm setting with the python language is an issue, you can always try running a sudo install of ruby 1.9.3 before the install scripts start...

So, if I were you, I'd
- add rabbitmq and run rake test to see if that'll be enough for you
- If that fails, I'd start looking at whether or not you need to add ruby to the mix

Once you sort out testing, you can probably still run pep8 as you have been, as a separate script. One thing I'm not sure of, is how coveralls would integrate. We'll cross that bridge when we come to it, either as a separate PR or part of this.

Thanks for looking at this...this has been something that we have not had the time to get to, but is very much needed. :)

**Comment by puhrez** [comment]
@benpatterson Thank you for all these resources.
EDIT:
so it looks like, just adding rabbitmq service worked, the build is only failing because pep8 violations.

**Comment by singingwolfboy** [comment]
@xbs13 this looks great to me -- thank you for all the work you've done already! I don't think you need to fix the pep8 violations if you don't want to, but at the very least we should make the test suite assert that we don't get _more_ pep8 violations over time.

Looks like there are currently 216 pep8 violations. Can you change the way Travis calls pep8 so that it pipes the result to a file, and then checks that the file doesn't have more than 216 lines? We do something pretty similar for pylint in the XBlock repo: https://github.com/edx/XBlock/blob/master/script/max_pylint_violations

**Comment by sarina** [comment]
@xbs13 - you may have to do a similar thing w/ pylint, as well, when you add in that linter (we use both pep8 and pylint at edX)

**Comment by sarina** [comment]
@xbs13 - are you able to bring this PR over the line? It's going to need to be adjusted so it's not failing on pep8, and you may want to squash up your commits a little bit if possible.

**Comment by puhrez** [comment]
@singingwolfboy  sounds good. I've just been busy these past few days.
@sarina "over the line"? Also to squash commits, that only requires a rebase right?

**Comment by sarina** [comment]
@xbs13 - "over the line" as in, put on the finishing touches so we can merge it.

Squashing instructions are here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request but yeah, it's an interactive rebase. That said - you may have problems if you try to reorder your commits, and commits such as `pumped mysql from 1.2.4 to 1.2.5` are reasonable to keep as-is. We tend to squash up commits that are like, "test to see if this works" into one larger commit that describes what work was actually done.

**Comment by sarina** [comment]
also you should add yourself to https://github.com/edx/xqueue/blob/master/AUTHORS

**Comment by puhrez** [comment]
@sarina  awesome! sounds great. thank you.

**Comment by puhrez** [comment]
@sarina awesome, thank you. I will read this and implement a little later.

**Comment by singingwolfboy** [comment]
Hey @xbs13, just wanted to see where you were on this. Do you think you'll be able finish this PR soon, or would you prefer for me to merge it as-is and finish up the last bits myself? I really, really want to get this merged in, but I don't want to just grab it away from you if you're not done.

**Comment by puhrez** [comment]
@singingwolfboy hey, I'm on this I've been incredible busy this week. but I'll get around to it by sunday for sure.

**Comment by xbs13** [comment]
@sarina I would like to rebase but rather than my commits, I'm presented with <code>noop</code>

**Comment by puhrez** [comment]
@sarina nevermind, figured it out :) I wasn't setting the commit hash correctly

**Comment by sarina** [comment]
Crazy Github! Can you hop on IRC? #edx-code on Freenode.

**Comment by puhrez** [comment]
So what more has to been done on this repo? I'm slightly lost. I rebased, I believe.

**Comment by sarina** [comment]
@xbs13 you didn't quite rebase, I'm not actually sure what you did. Check out these instructions: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

The only other things that needs to happen are (1) add yourself to https://github.com/edx/xqueue/blob/master/AUTHORS and (2) Make the build pass given the current number of pep8 violations:

> Can you change the way Travis calls pep8 so that it pipes the result to a file, and then checks that the file doesn't have more than 216 lines? We do something pretty similar for pylint in the XBlock repo: https://github.com/edx/XBlock/blob/master/script/max_pylint_violations

**Comment by singingwolfboy** [comment]
@xbs13 you got a clean build! :fireworks: :sunglasses: However, I just checked the build output on Travis, and I saw this section:

```
$ ./script/max_pylint_violations
./script/max_pylint_violations: line 4: pylint: command not found
0 pylint violations in total (max is 216)
```

It looks like `pylint` isn't installed, which causes the `max_pylint_violations` script to fail. However, because of the way it's written, it still has a 0 exit code, so Travis thinks everything went well. If you want to check pylint violations, that's fine, but you'll need to be sure that `pylint` is actually installed. Alternatively, you can just remove that `max_pylint_violations` script -- I'm not sure how many pylint violations we have, but I'm sure it's plenty. (I'd suggest that you just remove that pylint script.)

**Comment by puhrez** [comment]
forgot to remove the script command from the .travis whelp, currently working out rebasing.

**Comment by puhrez** [comment]
YAY!

**Comment by benpatterson** [comment]
Awesome. Thank you for the much-needed assistance, @xbs13, and for being open to our feedback on your changes.

:+1:

**Comment by singingwolfboy** [comment]
Amazing! :+1:

**Pull request merged**
