### PR TITLE
Fixes #73: changes version of newrelic package

### LINKED ISSUE #73: Not Found (newrelic/1.8.0.13)
https://pypi.python.org/simple/newrelic/1.8.0.13
Not Found (newrelic/1.8.0.13)

you get error:
Could not find a version that satisfies the requirement newrelic==1.8.0.13

problem file:
xqueue / requirements.txt

### PR DESCRIPTION
**Pull request by bogdan-kulynych**

### CODE REVIEW

**Comment by nedbat** [comment]
@bogdan-kulynych thanks for this tweak, sorry it has languished for so long.

Can you please sign and return a Contributor's Agreement as detailed in the edx-platform CONTRIBUTING file?  And/or, if you are affiliated with an institution, that is also helpful information.
Thanks.

**Comment by nedbat** [comment]
@e0d opinions?

**Comment by e0d** [comment]
At this point 2.8.0.7 is pretty old, the latest is 2.22.1.20.  If you resubmit with the version bumped, I'm :+1:

**Comment by hkim823** [comment]
Unless someone objects I am going to close this PR since PR #88 fixes the issue

**Pull request closed without merging**
