### PR TITLE
Added minimal docker setup

### PR DESCRIPTION
**Pull request by atnartur**
I added minimal docker configuration for easier start the system for local testing and development. In this case developer should have Docker engine and docker-compose installed on your machine. Then he can run only `docker-compose up` command in the root directory of project and xqueue server will start on 8000 port. 

I think this way is much easier than running with devstack.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @atnartur! I've created [OSPR-2836](https://openedx.atlassian.net/browse/OSPR-2836) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@atnartur  Sorry for delay, our bot was broken. Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by natabene** [comment]
@atnartur  Have you had a chance to sign contributor agreement? If so, can you send it over at your earliest convenience? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by natabene** [comment]
@atnartur We have not received your contributors agreement, so I am closing this PR for now. Please feel free to re-open should you decide to pursue this again.

**Comment by openedx-webhooks** [comment]
@atnartur Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue&entry.867055334=https://github.com/edx/xqueue/pull/223&entry.1484655318=https://github.com/atnartur&entry.752974735=2018-05-15+12:14&entry.1917517419=2019-01-16+17:29&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
